# Generated by Django 5.1.7 on 2025-04-12 14:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('text_2_column', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote']}), 1: ('wagtail.blocks.StructBlock', [[('column_1', 0), ('column_2', 0)]], {'template': 'base/text_2_column_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {})}),
        ),
    ]
